Feature: Create peers manually
Studia-Org/studia_frontend pull request #102
Opened 2024-03-06 09:47 UTC by rogeranyor

2024-03-06 11:37 UTC, Topiksit0 commented on src/features/courses/components/Activity/Components/PeerReview/CreatePeers.jsx
> +        console.log(peers)
console log

2024-03-06 11:50 UTC, Topiksit0 requested changes
- Creación de curso, el start_date no se añade y genera errores.
- Padding derecha
- Tour

2024-03-18 17:28 UTC, rogeranyor commented
Para la siguiente feature:

1. Hacer tour
2. Evaluacion de la peer review para el profe

2024-03-20 11:52 UTC, Topiksit0 commented
OK

2024-03-20 11:52 UTC, merged