FE147 - Feedback Mireia
Studia-Org/studia_frontend pull request #157
Opened 2024-06-12 10:45 UTC by Topiksit0

1.  Modificar cuestionarios para que puedan ser stackeables.
2.  Marcar los errores del cuestionario a final de pagina.
3.  Creacion de cursos con cuestionarios stackeables.
4.  Las task files tienen que estar entre la descripcion y el titulo.
5.  La submission tiene que estar junto al submit.
6.  En self-assesment la rubrica parece parte de la respuesta, cambiarlo.
7.  Cambiar sistema de evaluación self-assesment, no queda claro que sea del 1 al 10 y menos en función de la rúbrica.
8.  Saber en que curso estás en cada momento.
9.  Esconder la sidebar dentro de una activity y poder navegar siempre por el curso.
10.  En el calendar añadir el item del día concreto cuando le das a un día en concreto, por ejemplo 23.
11.  El go back no queda del todo claro.

2024-06-14 09:29 UTC, rogeranyor commented
**Probando con alumnotest15 en factors humans**

Al dar click en la barra 

![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/c8f1c28d-f316-4464-a5d4-cfe8a1ccac47)

Me pone undefined en la url y si estoy dentro de una actividad y tiro para atrás peta todo

![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/913757b1-4966-494c-9375-2f866dd2a40d)
sigo ? sigo
En la linea 118 de CourseInside.jsx  este código petaba le he puesto un && no peta pero quizas se carga algo no lo se.

![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/915edf8b-60df-4185-8f20-5e10054a4cf6)

sigo ? sigo
Primero sale open-ended-short

![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/0e76fe90-98cb-4c53-bf42-af3c0711064b)
sigo ? sigo
Y cuando lo cambio no vuelve aparecer y ademas se corta el texto, Creo que faltaría selección múltiple en el cuestionario

![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/d933ce7f-3d76-4671-87ac-624857bb5ea1)
sigo ? sigo
Este botón deberia ser un 'Create' submit se me hace rarísmo, no lo entendia

![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/edcfdfc1-f62e-4c88-ac09-2656887e8fc6)
sigo ? sigo
En la previsualización no se ven stacked

![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/4d7da68c-1d9c-4d65-a6bc-7c239d172a47)
sigo ? sigo
Si tienen el mismo nombre se marcan las dos, supongo que es un caso raro pero lo dejo por aqui no deberia pasar ( ha sido casualidad )

![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/dd88b1f6-3b72-45e3-95a6-83e721905228)
sigo ? sigo
He hecho que no salga el mensaje cuando no hay files

![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/8119f25c-7247-4b7a-a445-40fd531252ca)
sigo ? sigo
Este handleRemove de la lista de uploaded no borra las files de las base de datos, hay una funcion deleteFile(fileId) en activityComponent que antes lo hacía

![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/de2d1dfb-d20f-4fe6-b499-68953eb95296)
sigo ? sigo
Tambien he puesto la basura roja

![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/c8fdc08f-4eca-4521-a884-b8bfca90f384)

sigo ? sigo
Imagino que querias poner la hora en la que estamos, pq la pone 2h antes? tema de utc ?

![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/0f129d88-b1d2-4a0e-8bfe-d0e3c8699645)
sigo ? sigo
Despuse de entregar un self assestment me ha pasado esto 
![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/b9f18564-f486-4bf0-9163-1256931c063d)

Lo he vuelto a intentar y todo y asi que ha petado un post ha funcionado.... no entiendo na
![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/ad29d760-8c15-4a98-93a4-d2636f40d68b)

2024-06-14 09:42 UTC, rogeranyor requested changes
Cambiame cosas

2024-06-19 08:33 UTC, Topiksit0 commented
@rogeranyor todo cambiado

2024-06-19 14:22 UTC, rogeranyor requested changes
Bug:

https://github.com/Studia-Org/studia_frontend/assets/64661531/8b322fe6-7b88-4d51-805c-dab2c74d3741

2024-06-19 15:22 UTC, rogeranyor commented
> Bug:
> 
>  Factors.humans.testing.-.Uptitude.-.Brave.2024-06-19.16-19-25.mp4
El apartado de profesor, las task files están duplicadas... no sé si esto debería estar así
![image](https://github.com/Studia-Org/studia_frontend/assets/64661531/4b498b08-faf8-4df5-972e-c3601be7be69)

2024-06-20 17:27 UTC, merged